# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "receipts", :force => true do |t|
    t.column "date",           :datetime
    t.column "fname",          :string
    t.column "lname",          :string
    t.column "address",        :string
    t.column "state",          :string
    t.column "zip",            :integer
    t.column "city",           :string
    t.column "amount",         :float
    t.column "payment_method", :integer
    t.column "payment_extra",  :integer
    t.column "camper1",        :string
    t.column "camper1_id",     :string
    t.column "camper2",        :string
    t.column "camper2_id",     :string
    t.column "camper3",        :string
    t.column "camper3_id",     :string
    t.column "phone",          :string
  end

  create_table "states", :force => true do |t|
    t.column "name", :string
  end

end
