development: &default
  adapter: postgresql
  database: vce_development
  pool: 5
  timeout: 5000
  host: localhost
  min_messages: warning

test: &test
  adapter: postgresql
  database: vce_test
  pool: 5
  timeout: 5000
  host: localhost
  min_messages: warning
